trigger:
- main   # or your branch

pool:
  vmImage: ubuntu-latest

variables:
  target_path: /var/www/html/Assets   # Apache web root on EC2
  ec2_user: ubuntu             # default EC2 user
  ec2_host: 3.107.19.78       # your EC2 public IP

steps:
# Step 1: Checkout code
- checkout: self



# Step 3: Download SSH key
- task: DownloadSecureFile@1
  name: downloadSSHKey
  inputs:
    secureFile: 'sydneynew.pem'    # name of the key you uploaded

# Step 4: Deploy files to EC2
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Deploying files to EC2..."
      chmod 600 $(downloadSSHKey.secureFilePath)

      scp -o StrictHostKeyChecking=no -i $(downloadSSHKey.secureFilePath) -r * $(ec2_user)@$(ec2_host):$(target_path)

      ssh -o StrictHostKeyChecking=no -i $(downloadSSHKey.secureFilePath) $(ec2_user)@$(ec2_host) "sudo systemctl restart apache2"

      echo "✅ Deployment complete!"
